# 工作流名称。
name: kit/runtime
# 定义触发工作流的事件。
on:
  push:
    paths:
      - 'kit/runtime/**'
      - '.github/workflows/kit.runtime.yml'
  pull_request:
    paths:
      - 'kit/runtime/**'
      - '.github/workflows/kit.runtime.yml'
jobs:
  # 定义测试作业。
  test:
    # 作业的显示名称。
    name: Test
    env:
      KIT_TESTING_DIR: kit/runtime
    # 指定运行环境为最新版本的 Ubuntu。
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义测试矩阵，在多个 Go 版本上运行测试。
        # golangci-lint has version v1.64.8 built with go1.23.12
        # golangci-lint has version v1.64.8 built with go1.24.6 
        # 低版本会出现错误：
        # Error: can't load config: the Go language version (go1.23) used to build golangci-lint is lower than the targeted Go version (1.25)
        # Failed executing command with error: can't load config: the Go language version (go1.23) used to build golangci-lint is lower than the targeted Go version (1.25)
        # Error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25)
        # Failed executing command with error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25)
        go-version: ['1.25']
      # 某个版本失败时不中断其他版本的测试。
      fail-fast: false
    steps:
      # 使用官方的 checkout action 检出代码。
      - uses: actions/checkout@v4
      # 使用官方的 setup-go action 配置 Go 环境。
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # 使用矩阵中定义的 Go 版本。
          go-version: ${{ matrix.go-version }}
          # 启用依赖缓存，加速构建。
          cache: true
      # 使用 Makefile 中的 download 命令下载依赖。
      - name: Install dependencies
        run: |
          cd ${{ env.KIT_TESTING_DIR }}
          make download
      # 使用 Makefile 中的 verify 命令验证依赖完整性。
      - name: Verify dependencies
        run: |
          cd ${{ env.KIT_TESTING_DIR }}
          make verify
      # 运行 golangci-lint 进行代码质量检查。
      - name: Run golangci-lint
        run: |
          # 安装 golangci-lint。
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          # 显示版本信息。
          golangci-lint version
          # 运行 golangci-lint。
          cd ${{ env.KIT_TESTING_DIR }}
          make lint
      # 使用 Makefile 中的 test 命令运行测试。
      - name: Run tests
        run: |
          cd ${{ env.KIT_TESTING_DIR }}
          make test
      # 使用 Makefile 中的 coverage 命令运行测试并生成覆盖率报告。
      - name: Run tests with coverage
        run: |
          cd ${{ env.KIT_TESTING_DIR }}
          make coverage
      # 使用 Codecov 官方 action 上传覆盖率报告。
      # 上传后可以在 https://codecov.io 查看报告，需要先用 GitHub 账号登录并激活仓库。
      # 也可以通过 GitHub PR 中的 Codecov bot 评论查看覆盖率变化。
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # 指定覆盖率报告文件路径。
          file: ./out/coverage.txt
          # 上传失败时不中断 CI 流程。
          fail_ci_if_error: false
